version: '3.9'
services:
  meal-schedule:
    build: ./
    command: ./wait-for-postgres.sh db ./meal-schedule
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: meal-schedule

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5436:5432

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: ["-path", "migrations", "-database", "postgres://postgres:${DB_PASSWORD}@db:5432/postgres?sslmode=disable", "up"]
