version: '3.9'

services:
  meal-schedule:
    build: ./
    command: ./wait-for-postgres.sh db ./meal-schedule
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
    container_name: meal-schedule

  db:
    restart: always
    image: postgres:latest
    networks:
      new:
        aliases:
          - database
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    networks:
      - new

    depends_on:
      - db
    volumes:
      - .:/migration
    command: ["-path", "./migration", "-database",  "postgres://postgres:qwerty@database:5432/postgres?sslmode=disable", "up", "2"]
    links:
      - db


networks:
  new: