server:
  host: localhost
  port: 8000
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5

db:
  host: db
  port: 5432
  username: postgres
#  password: qwerty
  DBName: postgres
  SSLMode: disable

cloudinary:
    cloud_name: dlbd49n12
    api_key: 586786754446727
    api_secret: ko8XzWvDrVGu8-ELbXcYLGRYBtY
